# Generated by Django 5.0.6 on 2024-05-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
